### ISSUE TITLE
AptaTRACE does not complete

### ISSUE THREAD

**Issue by CentauriAlex** [drivenbyentropy/aptasuite#1]
Hi, 

Having run the v0.4 I am unable to get the AptaTRACE function to complete, please see attached log file.

Thanks.
[log_2017-08-21_08-33-11.txt](https://github.com/drivenbyentropy/aptasuite/files/1238185/log_2017-08-21_08-33-11.txt)

**Comment by drivenbyentropy** [comment]
Thank you reporting this. I think this was caused due to an unchecked condition when dealing with missing data between selection cycles in AptaTRACE. I have updated the current release with a fix (see 6619bb203fff199d5f2ef47a468f6b072a976f2e, v.0.4.1). Please download this version and let me know if it fixes the issue.

Thanks!

**Comment by CentauriAlex** [comment]
Hi, 

I have downloaded the v0.4.1 and re-run the AptaTRACE, which gets a bit further but gives a different error. Please see attached log file.

Thanks

[log_2017-08-22_07-32-09.txt](https://github.com/drivenbyentropy/aptasuite/files/1241254/log_2017-08-22_07-32-09.txt)

**Comment by drivenbyentropy** [comment]
I believe this is caused when AptaTRACE encounters a sequence which only occurs in a negative or counter selection. I have added this case to the code base (see aa02c4b7e8cbf7333f6aa908367d4ca71fdd746e). Please try again with v.0.4.2 and let me know if it works now.

Thanks

**Comment by CentauriAlex** [comment]
Hi, 

That appears to have fixed it!

Many Thanks

**Comment by drivenbyentropy** [comment]
Great. Thanks again for reporting this bug.
