### ISSUE TITLE
AptaPLEX bug - Paired-end reads parsing

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#11]
Hi,
Unfortunetely I've got a bug this time as well.
I'm using command-line aptasuite-0.5.3 via Windows PowerShell.
The files contain real-data derived subsets with 10000 reads each (forward and reverse), quality-filtered, etc.
Please find the aptasuite log and the powershell output.
[log_2018-02-16_11-28-10.txt](https://github.com/drivenbyentropy/aptasuite/files/1730961/log_2018-02-16_11-28-10.txt)
[errorlog160218.txt](https://github.com/drivenbyentropy/aptasuite/files/1730962/errorlog160218.txt)

**Comment by drivenbyentropy** [comment]
You have been busy :)

Could you please attach your configuration file as well? I strongly suspect this to be due to a misconfiguration (file path in windows must be escaped in a specific way) or corrupt fastq files as it is working without issues in my setup. 

If you are allowed to share the sequencing files, it would also help me to get debug the issue. 

Thanks!

**Comment by PJpb** [comment]
I'm sorry but I'm out of office for the weekend. I'll be able to share the files on Monday. It did work before however (with v0.4).

**Comment by PJpb** [comment]
Works both as CLI and GUI with demultiplexing etc. (tested only on one sample though)

**Comment by drivenbyentropy** [comment]
Perfect. Closing ticket.
