### ISSUE TITLE
GUI v0.6.7 - Motif Analysis window not scaled properly

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#33]
After the motif analysis (works fine now, thanks!) the main windows are not scaled properly - it seems that the bottom of the window is below the edge of the screen and I can't really help it. Also it doesn't allow to access the horizontal scroll bar and the Cardinality Chart is not displayed whole if all the right side windows are open.
This is how it should look like and looks like in other windows (Pool or Clusters):
![image](https://user-images.githubusercontent.com/32843053/36779753-4dd90b9c-1c71-11e8-935b-eb317b67748e.png)

And this is default view of the Motif Analysis window:
![image](https://user-images.githubusercontent.com/32843053/36779770-5e6d4de2-1c71-11e8-95c4-b4069f72ad85.png)

I can scroll sideways using a touchpad, so the functionality is there:
![image](https://user-images.githubusercontent.com/32843053/36779788-6b75832e-1c71-11e8-92dd-8af6beb28e84.png)

Or I can make the window wider:
![image](https://user-images.githubusercontent.com/32843053/36779805-7a7ae54e-1c71-11e8-90bc-105766f4a3a7.png)

But of course that's not how you want it to look like :)

Thanks for all the fixes, the software is really becoming a real thing! :) Keep it up!

**Comment by drivenbyentropy** [comment]
Thanks for the detailed report @PJpb. I think I did not encounter this issue because my monitors are large enough to not seeing this artifact in full screen mode. I have added scrollbars to the right column of the Pool, Cluster, and Motif tabs which should not scale correctly.

Let me know if [v0.6.9](https://github.com/drivenbyentropy/aptasuite/releases) provides the fix.

Thanks!

**Comment by PJpb** [comment]
Everything works now great, thanks!
