### ISSUE TITLE
AptaSuite fails to run AptaSim

### ISSUE THREAD

**Issue by hovercat** [drivenbyentropy/aptasuite#75]
Dear drivenbyentropy + Hoinka et al,

I am trying to simulate SELEX using AptaSuite 0.9.4 in command line mode with default configs as provided in the wiki.
First i tried running it natively on my machine (Lubuntu 19.04) which has OpenJDK 11.0.4. This did not work. Then I set up a fresh docker container with OpenJDK 1.8.0_222. AptaSim was started again in the container, but the error messages were exactly the same.
This was the command used:
`java -jar dckr/aptasuite-0.9.4/aptasuite-0.9.4.jar -simulate -config src/config/aptasim_default.config`

Could OpenJDK be the problem at hand?
I didn't get a log file by AptaSuite, but the console output is attached below. (stdout and stderr)
We had issues with this problem already some time ago, back then we tried to use trace and cluster.

Thank you very much for your help!
Hovercat

[aptasim_stdout_stderr.txt](https://github.com/drivenbyentropy/aptasuite/files/3814991/aptasim_stdout_stderr.txt)

**Comment by drivenbyentropy** [comment]
Hi, my apologies for not getting to this sooner.

These are the suggestions I have to get to the bottom of this. 
1) Have you tried running Aptasim using the graphical user interface? 
2) If this works (make sure you have openFX installed as you are using OpenJDK and to my knowledge they do not ship it by default) could you compare the generated configuration file with the one you are providing when using the command line?

OpenJDK should, to the best of my knowledge, not be the culprit here.

**Comment by hovercat** [comment]
Hello, thanks for your reply.

I got AptaSuite running with the GUI with OpenJFX 8u161-b12-1ubuntu2.
AptaSim with GUI worked, performing the simulation.
Apparently my config file was wrong, as I had missed the point in the wiki about specifying SelectionCycles and the exception's message didn't give me a hint on what could be wrong. 
The CLI version of AptaSuite works as well, provided the configuration file is valid. 

Thank you and sorry for bothering you! :+1:
