### ISSUE TITLE
Issue importing more than 4 files

### ISSUE THREAD

**Issue by dronc001** [drivenbyentropy/aptasuite#83]
I can run an analysis on 3 round files. If I try to add a 4th, the program abruptly closes when it tries to process the 4th file. 

[11:21:04 | INFO | Thread-5]: lib.aptamer.datastructures.MapDBSelectionCycle
Processing selection cycle R16 Target --This is the 3rd file-- 

[11:21:10 | CONFIG | Thread-5]: lib.aptamer.datastructures.MapDBSelectionCycle
Creating new file 'C:\Users\\Desktop\\\cycledata\16_R16 Target.mapdb' for selection cycle R16 Target. 

[11:21:10 | SEVERE | Thread-5]: lib.aptamer.datastructures.Experiment
Error invoking construtor of SelectionCycle backend 

[11:21:10 | SEVERE | Thread-5]: lib.aptamer.datastructures.Experiment
Error invoking SelectionCycle backend

**Comment by Bioanalytica** [comment]
I had the same issue when running very large datasets using the GUI implementation in Win7, Win10, and Ubuntu 18 & 20. I think it's an issue with java and some sort of security constraints to prevent buffer overflow, the exact same configuration runs flawlessly in the command line / terminal, respectively. I have not yet tried to allocate disk swap space to the GUI, which may fix the issue, I ran 9 rounds (from an old experiment, mine was far less) with ~133million seq reads and it executed nearly flawlessly; except the cluster/motif data was not exported even though it was processed due to improper syntax in config for Export.Files, so be sure to double check that your configuration comports exactly with the syntax outlined in the Wiki.

If you want to try it in command line or terminal, dedicating 100 Gb of SSD/M.2_NVMe, I also suggest increasing the process(es) priority/niceness, for full CPU utilization:

> java -Xmx100g -jar aptasuite.jar -parse -cluster -predict structure -trace -export pool,cycles,structure,clusters -config configuration.aptasuite

**Comment by drivenbyentropy** [comment]
Closing this, please feel free to reopen if this is still an issue.
